version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
    working_directory: ~/cocoabay
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - run: sudo apt install -y libsqlite3-dev libfreetype6-dev libmcrypt-dev libzip-dev libpng-dev libjpeg-dev nodejs
      - run: sudo docker-php-ext-configure gd --enable-gd-native-ttf --with-freetype-dir=/usr/include/freetype2 --with-png-dir=/usr/include --with-jpeg-dir=/usr/include
      - run: sudo docker-php-ext-install gd
      - run: sudo docker-php-ext-install zip
      - run: cp .env.testing .env

      # Composer
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      # NPM
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run production

      - run:
          name: Run PHPUnit Tests
          command: vendor/bin/phpunit
          environment:
            # Temporarily unset the SENTRY_DSN variable (automatically imported by dotenv from
            # the CircleCI environment) so intentional exceptions aren't reported to Sentry.
            SENTRY_DSN: ""

      - run: touch database/testing.sqlite

      - run:
          name: Start Chrome Driver
          command: vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve --env=dusk.testing
          background: true

      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk

      # Upload Dusk artifacts
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_artifacts:
          path: tests/Browser/console

      - deploy:
          name: Deploy to HostGator
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              php vendor/bin/process-dotenv .env.dist > .env
              ssh-keyscan -p 2222 -H ${HOST_IP} >> ~/.ssh/known_hosts
              scp -P 2222 .env ${HOST_USER}@${HOST_IP}:/tmp
              ssh -p 2222 ${HOST_USER}@${HOST_IP} "bash -s" < .circleci/deploy.sh
            fi